/** Versioned serialized boundary contracts; no runtime adapters. */
export {
  CAPTURE_ENVELOPE_LIMITS,
  CAPTURE_ENVELOPE_SPEC_VERSION,
  CAPTURE_ENVELOPE_V1_SCHEMA_ID,
  CAPTURE_METHODS,
  CAPTURE_SENDER_KINDS,
  captureEnvelopeV1JsonSchema,
  captureEnvelopeV1Schema,
  safeParseCaptureEnvelopeV1,
  type BoundaryValidationIssue,
  type CaptureEnvelopeV1,
  type CaptureEnvelopeV1ValidationResult,
  type CaptureMethod,
  type CaptureSenderKind,
} from "./capture-envelope.js";
export {
  EXTRACTION_METHODS,
  FIELD_EVIDENCE_SPEC_VERSION,
  extractorIdentityV1Schema,
  fieldCandidateV1Schema,
  fieldConflictV1Schema,
  fieldProvenanceV1Schema,
  fieldSourceReferenceV1Schema,
  userConfirmationV1Schema,
  type ExtractionMethod,
  type ExtractorIdentityV1,
  type FieldCandidateV1,
  type FieldConflictV1,
  type FieldProvenanceV1,
  type FieldSourceReferenceV1,
  type UserConfirmationV1,
} from "./field-evidence.js";
export {
  PORTABLE_ARCHIVE_LIMITS,
  PORTABLE_ARCHIVE_MANIFEST_SPEC_VERSION,
  PORTABLE_ARCHIVE_MANIFEST_V1_SCHEMA_ID,
  migrationHistoryEntryV1Schema,
  portableArchiveManifestV1JsonSchema,
  portableArchiveManifestV1Schema,
  portableAttachmentEntryV1Schema,
  portableDataEntryV1Schema,
  portableDatabaseEntryV1Schema,
  type MigrationHistoryEntryV1,
  type PortableArchiveManifestV1,
  type PortableAttachmentEntryV1,
  type PortableDataEntryV1,
  type PortableDatabaseEntryV1,
} from "./portable-archive.js";
export {
  PORTABLE_DATA_EXPORT_LIMITS,
  PORTABLE_DATA_EXPORT_SPEC_VERSION,
  PORTABLE_DATA_EXPORT_V1_SCHEMA_ID,
  portableDataExportV1JsonSchema,
  portableDataExportV1Schema,
  type PortableDataExportV1,
  type PortableDataRowV1,
} from "./portable-data-export.js";
export {
  DIAGNOSTIC_ATTRIBUTE_KEYS,
  DIAGNOSTIC_ATTRIBUTE_TOKENS,
  DIAGNOSTIC_CATEGORIES,
  DIAGNOSTIC_CODES,
  DIAGNOSTIC_EVENT_SPEC_VERSION,
  DIAGNOSTIC_EVENT_V1_SCHEMA_ID,
  DIAGNOSTIC_EVENT_NAMES,
  DIAGNOSTIC_OUTCOMES,
  DIAGNOSTIC_SEVERITIES,
  FORBIDDEN_DIAGNOSTIC_FIELD_PARTS,
  diagnosticAttributeKeySchema,
  diagnosticAttributeValueSchema,
  diagnosticEventV1JsonSchema,
  diagnosticEventV1Schema,
  type DiagnosticAttributeValue,
  type DiagnosticCategory,
  type DiagnosticEventV1,
  type DiagnosticOutcome,
  type DiagnosticSeverity,
} from "./diagnostic-event.js";
export {
  SUPPORT_BUNDLE_LIMITS,
  SUPPORT_BUNDLE_SPEC_VERSION,
  SUPPORT_BUNDLE_V1_SCHEMA_ID,
  supportBundleV1JsonSchema,
  supportBundleV1Schema,
  type SupportBundleV1,
} from "./support-bundle.js";
export { jsonValueSchema, type JsonValue } from "./primitives.js";
