import { readFile } from "node:fs/promises";
import path from "node:path";

import { beforeAll, describe, expect, it } from "vitest";

const repositoryRoot = path.resolve(import.meta.dirname, "..", "..");

let capability;
let archivePermission;
let nativeBoundary;

beforeAll(async () => {
  const tauriRoot = path.join(repositoryRoot, "apps", "desktop", "src-tauri");
  [capability, archivePermission, nativeBoundary] = await Promise.all([
    readFile(path.join(tauriRoot, "capabilities", "main.json"), "utf8").then(JSON.parse),
    readFile(
      path.join(tauriRoot, "permissions", "autogenerated", "native_archive_invoke.toml"),
      "utf8",
    ),
    readFile(path.join(tauriRoot, "src", "lib.rs"), "utf8"),
  ]);
});

describe("native archive capability", () => {
  it("grants only Coredrill's three exact custom commands", () => {
    expect(capability.permissions).toEqual([
      "allow-native-storage-invoke",
      "allow-native-secret-invoke",
      "allow-native-archive-invoke",
    ]);
    expect(
      capability.permissions.some(
        (permission) => permission.startsWith("dialog:") || permission.startsWith("fs:"),
      ),
    ).toBe(false);
  });

  it("binds the archive permission only to the picker-owned command", () => {
    expect(archivePermission).toContain('identifier = "allow-native-archive-invoke"');
    expect(archivePermission).toContain('commands.allow = ["native_archive_invoke"]');
    expect(nativeBoundary).toContain(".dialog()");
    expect(nativeBoundary).toContain(".file()");
    expect(nativeBoundary).toContain("service.invoke_archive_with_selected_path");
  });
});
