/** Storage ports, shared repository contracts, and migration coordination. */
export {
  createTransactionSemanticsSuite,
  DatabaseContractViolation,
  defineDatabaseContractSuite,
  runDatabaseContractSuite,
  type DatabaseContractAdapter,
  type DatabaseContractCase,
  type DatabaseContractRunResult,
  type DatabaseContractSuite,
  type TransactionContractProbe,
} from "./contract-harness.js";
export {
  createTrackerRepositoryContractSuite,
  type TrackerRepositoryContractSetup,
} from "./tracker-contract-harness.js";
export {
  sqlStatement,
  type DatabasePort,
  type DatabaseSession,
  type DatabaseTransaction,
  type ExecuteResult,
  type PortableDatabase,
  type QueryRow,
  type SqlStatement,
  type SqlValue,
  type StorageDiagnostics,
  type StorageHealth,
  type StoragePersistence,
} from "./database-port.js";
export {
  applySqlMigrations,
  defineSqlMigrations,
  type MigrationResult,
  type SqlMigration,
} from "./migrations.js";
export {
  AppSettingRepository,
  CompanyRepository,
  ContactRepository,
  FieldValueRepository,
  JobRepository,
  JobSourceRepository,
  LocationRepository,
  ProvenanceRepository,
  TrackerRepositoryConflictError,
  VaultRepository,
  createTrackerRepositories,
  replaceConfirmedFieldValue,
  type ConfirmedFieldValueReplacement,
  type NewAppSetting,
  type NewCompany,
  type NewCompanyAlias,
  type NewContact,
  type NewContactPointProvenance,
  type NewFieldValue,
  type NewJob,
  type NewJobSource,
  type NewLocation,
  type NewProvenance,
  type NewSourceSnapshot,
  type TrackerRepositories,
  type TrackerRepositoryConflictCode,
} from "./tracker-repositories.js";
export type {
  AppSettingRecord,
  CompanyAliasRecord,
  CompanyRecord,
  ContactPointProvenanceRecord,
  ContactRecord,
  FieldConfirmationRecord,
  FieldValueRecord,
  JobRecord,
  JobSourceRecord,
  LocationPrecision,
  LocationRecord,
  ProvenanceExtractionMethod,
  ProvenanceRecord,
  SourceSnapshotRecord,
  VaultRecord,
} from "./tracker-records.js";
