/** Storage ports, shared repository contracts, and migration coordination. */
export {
  advancingAuditTimestamp,
  auditTimestamps,
  type AuditTimestamps,
} from "./audit-integrity.js";
export {
  createTransactionSemanticsSuite,
  DatabaseContractViolation,
  defineDatabaseContractSuite,
  runDatabaseContractSuite,
  type DatabaseContractAdapter,
  type DatabaseContractCase,
  type DatabaseContractRunResult,
  type DatabaseContractSuite,
  type TransactionContractProbe,
} from "./contract-harness.js";
export {
  createPipelineRepositoryContractSuite,
  type PipelineRepositoryContractSetup,
} from "./pipeline-contract-harness.js";
export {
  createDocumentRepositoryContractSuite,
  type DocumentRepositoryContractSetup,
} from "./document-contract-harness.js";
export {
  AttachmentManifestRepository,
  DocumentRepository,
  DocumentRepositoryConflictError,
  DocumentVersionRepository,
  createDocumentRepositories,
  type DocumentRepositories,
  type DocumentRepositoryConflictCode,
  type NewAttachmentManifest,
  type NewDocument,
  type NewDocumentVersion,
  type NewDocumentVersionAttachment,
} from "./document-repositories.js";
export type {
  AttachmentManifestRecord,
  DocumentKind,
  DocumentRecord,
  DocumentVersionAttachmentRecord,
  DocumentVersionRecord,
} from "./document-records.js";
export {
  ApplicationRepository,
  InteractionRepository,
  InterviewRepository,
  NextActionRepository,
  PipelineRepositoryConflictError,
  ReminderRepository,
  StatusDefinitionRepository,
  StatusEventRepository,
  changePipelineStatus,
  completeNextAction,
  createPipelineRepositories,
  setNextAction,
  type NewApplication,
  type NewInteraction,
  type NewInterview,
  type NewNextAction,
  type NewReminder,
  type NewStatusDefinition,
  type PipelineRepositories,
  type PipelineRepositoryConflictCode,
} from "./pipeline-repositories.js";
export type {
  ApplicationRecord,
  InteractionDirection,
  InteractionRecord,
  InterviewRecord,
  NextActionRecord,
  NextActionState,
  ReminderRecord,
  ReminderState,
  StatusDefinitionRecord,
  StatusEventRecord,
} from "./pipeline-records.js";
export {
  createTrackerRepositoryContractSuite,
  type TrackerRepositoryContractSetup,
} from "./tracker-contract-harness.js";
export {
  sqlStatement,
  type DatabasePort,
  type DatabaseSession,
  type DatabaseTransaction,
  type ExecuteResult,
  type PortableDatabase,
  type QueryRow,
  type SqlStatement,
  type SqlValue,
  type StorageDiagnostics,
  type StorageHealth,
  type StoragePersistence,
} from "./database-port.js";
export {
  applySqlMigrations,
  defineSqlMigrations,
  type MigrationResult,
  type SqlMigration,
} from "./migrations.js";
export {
  AppSettingRepository,
  CompanyRepository,
  ContactRepository,
  DeviceRepository,
  FieldValueRepository,
  JobRepository,
  JobSourceRepository,
  LocationRepository,
  ProvenanceRepository,
  TrackerRepositoryConflictError,
  VaultRepository,
  createTrackerRepositories,
  replaceConfirmedFieldValue,
  type ConfirmedFieldValueReplacement,
  type NewAppSetting,
  type NewCompany,
  type NewCompanyAlias,
  type NewContact,
  type NewContactPointProvenance,
  type NewDevice,
  type NewFieldValue,
  type NewJob,
  type NewJobSource,
  type NewLocation,
  type NewProvenance,
  type NewSourceSnapshot,
  type TrackerRepositories,
  type TrackerRepositoryConflictCode,
} from "./tracker-repositories.js";
export type {
  AppSettingRecord,
  CompanyAliasRecord,
  CompanyRecord,
  ContactPointProvenanceRecord,
  ContactRecord,
  DeviceRecord,
  FieldConfirmationRecord,
  FieldValueRecord,
  JobRecord,
  JobSourceRecord,
  LocationPrecision,
  LocationRecord,
  ProvenanceExtractionMethod,
  ProvenanceRecord,
  SourceSnapshotRecord,
  VaultRecord,
} from "./tracker-records.js";
export {
  createViewRepositoryContractSuite,
  type ViewRepositoryContractSetup,
} from "./view-contract-harness.js";
export {
  SavedViewRepository,
  TagRepository,
  ViewRepositoryConflictError,
  createViewRepositories,
  type NewSavedView,
  type NewTag,
  type SavedViewUpdate,
  type ViewRepositories,
  type ViewRepositoryConflictCode,
} from "./view-repositories.js";
export type { SavedViewRecord, SavedViewScope, TagRecord } from "./view-records.js";
