/** Use-case orchestration and query DTOs over domain ports. */
export {
  defineCommand,
  defineQuery,
  type ApplicationCommand,
  type ApplicationCommandName,
  type ApplicationOperationContext,
  type ApplicationQuery,
  type ApplicationQueryName,
} from "./operation.js";
export {
  APPLICATION_ERROR_CODES,
  applicationError,
  applicationFailure,
  applicationSuccess,
  type ApplicationError,
  type ApplicationErrorCode,
  type ApplicationResult,
} from "./result.js";
export {
  VAULT_DIAGNOSTIC_ISSUE_CODES,
  VAULT_LIFECYCLE_ERROR_CODES,
  VAULT_STORAGE_HEALTH_VALUES,
  VAULT_STORAGE_PERSISTENCE_VALUES,
  VaultLifecycleError,
  createVaultOperations,
  type CreateVaultInput,
  type CreateVaultPortInput,
  type OpenVaultInput,
  type OpenVaultPortInput,
  type VaultDiagnosticIssueCode,
  type VaultDiagnosticsDto,
  type VaultDto,
  type VaultLifecycleErrorCode,
  type VaultLifecyclePort,
  type VaultOperationDependencies,
  type VaultOperations,
  type VaultSessionDto,
  type VaultStorageHealth,
  type VaultStoragePersistence,
} from "./vault.js";
